nome = str(input('Digite o seu nome completo:')).strip()
print('Analisando o seu nome...')
print('O seu nome em letra maíuscula é: {}'.format(nome.upper()))
print('O seu nome em letrar minusculas é:{}'.format(nome.lower()))
print('Seu nome tem ao tanto {} letras'.format(len(nome)- nome.count(' ')))
#print('O seu primeiro nome possui {} letras'.format(nome.find(' ')))
separador = nome.split.nome()
print('O seu nome é {} e ele possui {} letras'.format(separador[0], len(separador[0])))
