n = int(input('Digite um número para tabuada'))
print('-----------------------')
print('      T A B U A D A D O D J A B O      ')
print('{} X {} = {}'.format(n, 1, n*1))
print(' {} X {} = {}'.format(n, 2, n*2))
print('{} X {} = {}'.format(n, 3, n*3))
print('{} X {} = {}'.format(n, 4, n*4))
print('{} X {} = {}'.format(n, 5, n*5))
print('{} X {} = {}'.format(n, 6, n*6))
print('{} X {} = {}'.format(n, 7, n*7))
print('{} X {} = {}'.format(n, 8, n*8))
print('{} X {} = {}'.format(n, 9, n*9))
print('{} X {} = {}'.format(n, 10, n*10))
print('{} X {} = {}'.format(n, 11, n*11))
print('{} X {} = {}'.format(n, 12, n*12))
print('{} X {} = {}'.format(n, 13, n*13))
print('{} X {} = {}'.format(n, 14, n*14))
print('{} X {} = {}'.format(n, 15, n*15))
print('{} X {} = {}'.format(n, 16, n*16))
print('{} X {} = {}'.format(n, 17, n*17))
print('{} X {} = {}'.format(n, 18, n*18))
print('{} X {} = {}'.format(n, 19, n*19))
print('{} X {} = {}'.format(n, 20, n*20))
print('{} X {} = {}'.format(n, 21, n*21))
print('{} X {} = {}'.format(n, 22, n*22))
print('-----------------------')
